services:
  sabnzbd-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sabnzbd-mcp
    ports:
      - "${SABNZBD_MCP_PORT:-9152}:${SABNZBD_MCP_PORT:-9152}"
    env_file:
      - .env
    volumes:
      - sabnzbd-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6972/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - sabnzbd-mcp-network

volumes:
  sabnzbd-logs:

networks:
  sabnzbd-mcp-network:
    driver: bridge 