services:
  sabnzbd-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sabnzbd-mcp
    labels:
      - com.centurylinklabs.watchtower.enable=false
    ports:
      - "${SABNZBD_MCP_PORT:-9152}:${SABNZBD_MCP_PORT:-9152}"
    env_file:
      - .env
    volumes:
      - /mnt/cache/appdata/sabnzbd-mcp/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9152/health"]
      interval: 30s 
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - jakenet

networks:
  jakenet:
    external: true 